### ISSUE TITLE
TTIN not working?

### ISSUE THREAD

**Issue by michaelsauter** [puma/puma#1103]
### Steps to reproduce

1) Start Puma in clustered mode, e.g. with 2 workers

```
bind "tcp://0.0.0.0:3000"
workers 2
threads 1, 1
prune_bundler
environment 'development'
pidfile File.expand_path("../../tmp/puma/pid", __FILE__)
state_path File.expand_path("../../tmp/puma/state", __FILE__)
activate_control_app
```

2) `kill -s TTIN <PID of master process>`
### Expected behavior

I expected Puma to spawn a new worker.
### Actual behavior

Nothing seems to happen.
### System configuration

**Ruby version**: 2.2.4

I had a look at the implementation (https://github.com/puma/puma/blob/master/lib/puma/cluster.rb#L336) but I couldn't figure out why it wouldn't work. Also, TTOU works as expected.

Or is my initial assumption wrong that TTIN increases the worker count beyond the amount specified in the configuration?

**Comment by steakknife** [comment]
TTIN and TTOU aren't working as expected. 

TTIN doesn't seem to do anything

TTOU appears to just kill a worker at random and then another one takes its place.

**Comment by pchaganti** [comment]
👍

**Comment by steakknife** [comment]
Why did you close this issue? It's still broken on HEAD.

**Comment by nateberkopec** [comment]
Fixed by #1118

**Comment by nateberkopec** [comment]
TTOU works as expected, but it isn't logging anything. I'll open a separate issue.

**Comment by steakknife** [comment]
Ah that makes sense. Thanks for weekend FOSS hacking.

**Comment by nateberkopec** [comment]
Reopening after the revert for 3.6.2.

**Comment by fidalgo** [comment]
Any plans to get this?

**Comment by nateberkopec** [comment]
Fixed on master, just forgot about this issue 👍

**Comment by fidalgo** [comment]
Sorry @nateberkopec but can you point the commit or the PR?

If I start a Rails server `rails s` with:
 ```
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.3-p222), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
```
I still can't see the Backtrace, and by the commit messages after 3.7.0 I can't infer the commit on this.

**Comment by nateberkopec** [comment]
@fidalgo Sorry, can you expand on what you expect to happen? This issue is for TTIN signals, which should increase worker count.

**Comment by fidalgo** [comment]
@nateberkopec 
Staring a rails server with `rails s`
If I send the `TTIN` signal to the puma process: 
```
ps uax | grep puma
fidalgo   3703 18.6  1.3 1296600 110912 pts/3  Sl+  16:29   0:02 puma 3.7.0 (tcp://0.0.0.0:3000) [registadora]
```

The process continue to run:
```
kill -TTIN 3703
[fidalgo@localhost registadora]$ ps uax | grep puma
fidalgo   3703  5.5  1.3 1296600 110912 pts/3  Tl   16:29   0:02 puma 3.7.0 (tcp://0.0.0.0:3000) [registadora]
```
but the `rails s` output console I have a message saying the process was stopped:
```
rails s
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.3-p222), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

[1]+  Stopped                 rails s
```
Note that puma is in single mode!

**Comment by evanphx** [comment]
@fidalgo You can't send it TTIN in single mode, so it's basically an invalid signal, that's why it just exits.
