### ISSUE TITLE
Error reached top of thread-pool: EOFError (EOFError)

### ISSUE THREAD

**Issue by vincentwoo** [puma/puma#1502]
Frequently for us in dev, puma hits an error in its thread pool, grinding the web server to a halt. This happens on page refreshes on our Rails app. I'm making an issue out of desperation, but I have not a lot to go on.

It appears this block catches some kind of internal error, but no backtrace is attached for us:

https://github.com/puma/puma/blob/master/lib/puma/thread_pool.rb#L121

```ruby
          begin
            block.call(work, *extra)
          rescue Exception => e
            STDERR.puts "Error reached top of thread-pool: #{e.message} (#{e.class})"
          end
```

After a few of those in the logs, we also sometimes see:

`16:51:09 web.1     | Error in reactor loop escaped: undefined method `join' for nil:NilClass (NoMethodError)`

Does anyone have a hunch about where this might be coming from?

### System configuration

**Ruby version**: 2.5.0
**Rails version**: 5.1.4
**Puma version**: 3.11.0

**Comment by vincentwoo** [comment]
This is probably related to https://github.com/puma/puma/issues/1483, since we also run SSL in dev.

**Comment by vincentwoo** [comment]
If relevant, this is our puma config:

```ruby
workers Integer(ENV['WEB_CONCURRENCY'] || 1) # 1 worker 5 threads in dev
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

_port = ENV['PORT'] || 8080
_environment = ENV['RACK_ENV'] || 'development'

if _environment == 'development' && File.exists?('/etc/ssl/localhost.ssl.key')
  ssl_bind '0.0.0.0', _port, {
    key: '/etc/ssl/localhost.ssl.key',
    cert: '/etc/ssl/localhost.ssl.crt',
    verify_mode: 'none'
  }
else
  port _port
end

rackup DefaultRackup
environment _environment

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end

plugin :tmp_restart
```

**Comment by vincentwoo** [comment]
After a lot of print debugging, I believe the exception-throwing line is: https://github.com/puma/puma/blob/master/lib/puma/minissl.rb#L66

```ruby
@engine.inject(data)
```

when data is `nil`. This seems to happen pretty reliable once I added a bunch of print debugging, suggesting the problem is timing-related. The exception happens after the server has hung for many seconds, suggesting that the root cause is deeper.

**Comment by vincentwoo** [comment]
This is about as far as I am liable to get on my own, I fear. Help is desperately appreciated!

**Comment by vincentwoo** [comment]
Oh, in case this is related: I'm running OSX. It's possible that the issues outlined in https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/ matter.

**Comment by jtzero** [comment]
another data point, 
I have the same issue but on  
`ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin16]` 
and Sierra (not high sierra)

**Comment by rrevi** [comment]
So I updated to 3.11.2 to fix this issue. While the issue log errors mentioned here no longer show up, I am now getting the following errors in the puma.log file with most HTTP requests (over SSL of course):

> === puma startup: 2018-02-01 08:00:55 -0500 ===
=== puma startup: 2018-02-01 08:00:55 -0500 ===
Error reached top of thread-pool: EOFError (EOFError)
Error reached top of thread-pool: EOFError (EOFError)
Error reached top of thread-pool: EOFError (EOFError)
Error reached top of thread-pool: EOFError (EOFError)
Error reached top of thread-pool: EOFError (EOFError)
Error reached top of thread-pool: EOFError (EOFError)Error reached top of thread-pool: EOFError (EOFError)
Error reached top of thread-pool: EOFError (EOFError)

anyone have any idea what could be going on? I haven't noticed any bad user experience yet (e.g. puma crash or http request hang)

Thanks,
Rafael

**Comment by chytreg** [comment]
I have exactly the same issue and cannot track down the cause either.

**Comment by rssluca** [comment]
Same issue here although non disruptive.

**Comment by MarkMurphy** [comment]
Also having the same problem

**Comment by gcoderre** [comment]
I'm seeing the same issue after updating to 3.11.2 while using SSL:

Puma: 3.11.2
Ruby: 2.4.3p205
Rails: 5.1.5
OS: macOS 10.13.1

**Comment by kylekyle** [comment]
Also getting this with the exact same setup and versions as @gcoderre but on Rack/Roda not Rails.

**Comment by kylekyle** [comment]
Can we reopen this? I'm seeing it on both OS X and RHEL7 ....

**Comment by dbpqdb** [comment]
+1

Seeing same issue as @rrevi on Puma 3.11.2, Ubuntu 16.04.

**Comment by tuwukee** [comment]
hey @evanphx,
`Error reached top of thread-pool: EOFError (EOFError)` is fixed with your commit b9ff900

but I'm still getting EOFErrors with puma server
```
2018-03-06 14:24:05 +0300: Read error: #<EOFError: EOFError>

/Users/july/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.11.3/lib/puma/client.rb:292:in `try_to_finish'
/Users/july/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.11.3/lib/puma/client.rb:106:in `reset'
/Users/july/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:450:in `process_client'
/Users/july/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:302:in `block in run'
/Users/july/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.11.3/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Your change adds exception handling for `client.eagerly_finish` method call https://github.com/puma/puma/blob/master/lib/puma/server.rb#L280

The EOFError is also can be thrown by `client.reset` method https://github.com/puma/puma/blob/master/lib/puma/server.rb#L450

Can you fix this one as well please?
Thanks!

**Comment by nateberkopec** [comment]
Reopening until @tuwukee's comment is addressed.

**Comment by bruno-campos** [comment]
I'm also seeing the same error reported by tuwukee on 3.11.4

```
2018-06-01 12:55:57 +0000: Read error: #<EOFError: EOFError>
/usr/local/bundle/gems/puma-3.11.3/lib/puma/client.rb:292:in `try_to_finish'
/usr/local/bundle/gems/puma-3.11.3/lib/puma/client.rb:106:in `reset'
/usr/local/bundle/gems/puma-3.11.3/lib/puma/server.rb:450:in `process_client'
/usr/local/bundle/gems/puma-3.11.3/lib/puma/server.rb:302:in `block in run'
```

Ruby 2.5.0
Rails 5.2.0

**Comment by UniqueTokens** [comment]
+1
Same problem here as for tuwukee and bruno-campos, running in ruby:2.6.2 Docker image (Debian stretch). But only occurs on our hosted virtual production Server (Ubuntu 18.04.2) with the SSL key and certificate assigned to us from our webhoster in Puma ssl_bind (verify_mode: none). Self-signed SSL certificates on our local and hosted development systems do not generate errors (also tested in Docker, also verify_mode: none).

**Comment by andrykonchin** [comment]
Looks like the issue wis `EOFError` is already fixed.

The code version where the `EOFError` error was reported to happen - [source code](https://github.com/puma/puma/blob/v3.11.3/lib/puma/client.rb#L104-L106). Currently any IO error is rescued and swallowed here [source code](https://github.com/puma/puma/blob/v4.3.3/lib/puma/client.rb#L131-L138).

This change was introduce in https://github.com/puma/puma/pull/1728 and released in v4.0.0 ([Changelog](https://github.com/puma/puma/blob/master/History.md#400--2019-06-25))

**Comment by ricvillagrana** [comment]
I am still having this issue on a Docker image `ruby:2.5.5`.

Versions:
```
Ruby: 2.5.5
Rails: 5.2
puma: 4.3.3
```

**Comment by akkhilp** [comment]
Can we reopen this issue. I'm trying to run a RubyOnRails web app server with Puma and the error is "Error reached top of thread-pool: undefined method `>=' for nil:NilClass (NoMethodError)"

Rails: 6.1.x
Puma: 6.4.x

**Comment by dentarg** [comment]
If you can reproduce the issue, you can open a new issue. Please include clear steps for anyone to reproduce the issue if you open one.
